#!/usr/bin/env node
var filesystem = require('fs');
var config = JSON.parse(filesystem.readFileSync('config.json'));

var program = require('commander');
program.parse(process.argv);

var args = program.args;

if (args.length < 2) {
  console.error('You must specify a space id and a chart id');
  process.exit(1);
}

var space = args[0];
var chart = args[1];

var Client = require('node-rest-client').Client;
var options_auth = { user: config.librato_token, password: config.librato_apikey };

var client = new Client(options_auth);

client.get(config.base_url + "spaces/" + space + "/charts/" + chart,
           function (data, response) {
              console.log(JSON.stringify(remove_ids(data), null, 2));
           });

var remove_ids = function(data) {
  delete data.id;
  for(var i = 0; i < data.streams.length; i++) {
    delete data.streams[i].id;
  }

  return data;
}
