#!/usr/bin/env node
'use strict';

var config = require('./modules/librato-cli-config');
var flow = require('./modules/librato-cli-flow');

var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 1) {
  flow.error('No API key specified, nothing changed');
  return;
}

config.setApiKey(args[0]);
