#!/usr/bin/env node
var config = require('./modules/librato-cli-config');

var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 1) {
  console.error('No token specified, nothing changed');
  process.exit(1);
}

config.setToken(args[0]);
