#!/usr/bin/env node
'use strict';

var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var moment = require('moment');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (!args.length) {
  flow.error('You must specify a metric name');
  return;
}

if (args.length < 2) {
  flow.error('You should supply the number of seconds in the past to query for');
  return;
}

if (args.length < 3) {
  flow.error('You should supply the source(s) for which to fetch measurements for (e.g. *)');
  return;
}

if (args.length < 4) {
  flow.error('You should supply the resolution for which to fetch measurements for (e.g. 60 seconds)');
  return;
}

var getMetricOverSpan = function(metricName, startTime, endTime, source, resolution) {
  var endPoint = config.baseUrl + 'metrics/' + metricName +
                  '?start_time=' + startTime +
                  '&end_time=' + endTime +
                  '&source=' + source +
                  '&resolution=' + resolution;

  client.get(endPoint, function (data, response) {
                         console.log(JSON.stringify(data, null, 2));
                         if (data.query && data.query.next_time) {
                           getMetricOverSpan(metricName, data.query.next_time, endTime);
                         }
                       });
};

var getMetric = function(metricName, numberOfSeconds, source, resolution) {
  var startTime = moment().subtract(numberOfSeconds, 'seconds').unix();
  var endTime = moment().unix();

  getMetricOverSpan(metricName, startTime, endTime, source, resolution);
};

getMetric(args[0], args[1], args[2], args[3]);
