#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program
  .parse(process.argv);
var args = program.args;

var endPoint = config.baseUrl + 'v1/sources';
client.get(endPoint,
           function printResponse(data, response) {
              console.log(JSON.stringify(data, null, 2));
           });
