#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program.parse(process.argv);

var args = program.args;

if (!args.length) {
  console.error('You must specify a space id');
  process.exit(1);
}

var getSpace = function(spaceId) {
  var endPoint = config.baseUrl + "spaces/" + spaceId;
  client.get(endPoint, function printResponse(data, response) {
                        console.log(JSON.stringify(data, null, 2));
                      });
};

getSpace(args[0]);
