#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');

var endPoint = config.baseUrl + 'v1/alerts';
client.get(endPoint,
           function (data, response) {
              console.log(JSON.stringify(data, null, 2));
           });
