#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program
  .parse(process.argv);
var args = program.args;

var endPoint = config.baseUrl + 'v1/alerts';
client.get(endPoint,
           function (data, response) {
             var alerts = data.alerts;

             if (alerts) {
               alerts.forEach(function(alert) {
                 var serviceIds = [];
                 alert.services.forEach(function(service) {
                   serviceIds.push(service.id);
                 });

                 alert.services = serviceIds;
               });

               console.log(JSON.stringify(alerts, null, 2));
             }
           });
