#!/usr/bin/env node
var filesystem = require('fs');
var config = JSON.parse(filesystem.readFileSync('config.json'));

var program = require('commander');
program.parse(process.argv);

var attributes = program.args;
var metric_name = attributes[0];

if (attributes.length < 2) {
  console.error('No attributes specified, nothing was done');
  process.exit(1);
}

var Client = require('node-rest-client').Client;
var options_auth = { user: config.librato_token, password: config.librato_apikey };

var attribute_data = '';

for (var i = 1, len = attributes.length; i < len; i++) {
  if (attribute_data.length > 0) {
    attribute_data += '&';
  }

  var attribute_pair = attributes[i].split('=');
  attribute_data += 'attributes[' + attribute_pair[0] + ']=' + attribute_pair[1];
}

var client = new Client(options_auth);

var payload = {
  data: attribute_data,
  headers: { "Content-Type": "application/x-www-form-urlencoded" }
};

client.put(config.base_url + "metrics/" + metric_name, payload,
           function (data, response) {
              console.log(response.statusCode + ': ' + response.statusMessage);
              console.log(JSON.stringify(data, null, 2));
           });
