#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');

var endPoint = config.baseUrl + "sources";
client.get(endPoint,
           function printResponse(data, response) {
              console.log(JSON.stringify(data, null, 2));
           });
