#!/usr/bin/env node
var program = require('commander');
program
  .version('0.3.0')
  .command('list', 'list all librato alerts')
  .command('import <alert_definition>', 'import the definition for one or more alerts, all as newly created alerts')
  .command('migrate <legacy_alert_definition>', 'migrates one or more legacy alerts to equivalent multidimensional alerts')
  .parse(process.argv);
