#!/usr/bin/env node
var program = require('commander');
program
  .version('0.0.1')
  .command('chart', 'manage librato charts')
  .command('source', 'manage librato sources')
  .command('metric', 'manage librato metrics')
  .command('space', 'manage librato spaces')
  .parse(process.argv);
