#!/usr/bin/env node
var program = require('commander');
program
  .version('0.3.0')
  .command('list', 'list all librato alerts')
  .command('migrate [legacy_alert_definition]', 'migrates a legacy alert to an equivalent tagged alert')
  .parse(process.argv);
