#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (attributes.length < 1) {
  console.error('You must specify the full metric name of the metric you wish to alter');
  process.exit(1);
}

if (attributes.length < 2) {
  console.error('No attributes were specified, nothing was done');
  process.exit(1);
}

var updateAttributes = function(metricName, attributes) {
  var attributeData = '';

  for (var i = 1; i < attributes.length; i++) {
    if (attributeData.length > 0) {
      attributeData += '&';
    }

    var attributeKeyValuePair = attributes[i].split('=');
    attributeData += 'attributes[' + attributeKeyValuePair[0] + ']=' + attributeKeyValuePair[1];
  }

  var payload = {
    data: attributeData,
    headers: { "Content-Type": "application/x-www-form-urlencoded" }
  };

  var endPoint = config.baseUrl + "metrics/" + metric_name;
  client.put(endPoint, payload, function (data, response) {
                                  console.log(response.statusCode + ': ' + response.statusMessage);
                                  console.log(JSON.stringify(data, null, 2));
                                });
};

updateAttributes(args[0], args.slice(1));
