#!/usr/bin/env node
'use strict';

var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 1) {
  flow.error('You must specify the metric name or pattern of the metric you wish to update');
  return;
}

if (args.length < 2) {
  flow.error('No properties were specified, nothing was done');
  return;
}

var getMatchingMetrics = function(metricName, properties) {
  var endPoint = config.baseUrl + 'metrics?name=' + metricName;
  client.get(endPoint, function (data, response) {
                         for (var i = 0; i < data.metrics.length; i++) {
                           var metric = data.metrics[i];
                           console.log('Updating properties for: ' + metric.name);
                           updateProperties(metric.name, properties);
                         }
                       });
};

var updateProperties = function(metricName, properties) {
  var propertyData = '';

  for (var i = 1; i < properties.length; i++) {
    if (propertyData.length > 0) {
      propertyData += '&';
    }

    propertyData += properties[i];
  }

  var payload = {
    data: propertyData,
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
  };

  var endPoint = config.baseUrl + 'metrics/' + metricName;
  client.put(endPoint, payload, function (data, response) {
                                  console.log(response.statusCode + ': ' + response.statusMessage);
                                  console.log(JSON.stringify(data, null, 2));
                                });
};

getMatchingMetrics(args[0], args.slice(0));
