#!/usr/bin/env node
var filesystem = require('fs');
var config = JSON.parse(filesystem.readFileSync('config.json'));

var program = require('commander');
program.parse(process.argv);

var args = program.args;

if (args.length < 1) {
  console.error('You must specify a space definition to import a space');
  process.exit(1);
}

var space_definition = JSON.parse(args[0]);

var Client = require('node-rest-client').Client;
var options_auth = { user: config.librato_token, password: config.librato_apikey };

var client = new Client(options_auth);

var create_space_payload = {
  data: JSON.stringify({ name: space_definition.name }),
  headers: { "Content-Type": "application/json" }
};

client.post(config.base_url + "spaces", create_space_payload,
           function (data, response) {
              console.log(response.statusCode + ': ' + response.statusMessage);
              console.log(JSON.stringify(data, null, 2));

              var new_space_id = data.id;

              for(var i = 0; i < space_definition.charts.length; i++) {
                var create_chart_payload = {
                    data: space_definition.charts[i],
                    headers: { "Content-Type": "application/json" }
                };

                client.post(config.base_url + "spaces/" + new_space_id + "/charts", create_chart_payload,
                           function (data, response) {
                              console.log(response.statusCode + ': ' + response.statusMessage);
                              console.log(JSON.stringify(data, null, 2));
                           });
              }
           });
