#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var moment = require('moment');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (!args.length) {
  flow.error('You must specify a metric name');
  return;
}

if (args.length < 2) {
  flow.error('You should supply the number of seconds in the past to query for');
  return;
}

var getMetric = function(metricName, numberOfSeconds) {
  var endPoint = config.baseUrl + "metrics/" + metricName
    + "?start_time=" + moment().subtract(numberOfSeconds, 'seconds').unix()
    + "&end_time=" + moment().unix() + "&resolution=60";
  client.get(endPoint, function (data, response) {
                         console.log(JSON.stringify(data, null, 2));
                       });
};

getMetric(args[0], args[1]);
