#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var flow = require('./modules/librato-cli-flow');

var program = require('commander');

program
  .usage('<api_key>')
  .parse(process.argv);
var args = program.args;

if (args.length < 1) {
  program.outputHelp();
  flow.error('No API key specified, no configuration changes were applied');
  return;
}

config.setApiKey(args[0]);
