#!/usr/bin/env node
var program = require('commander');
program
  .version('0.0.1')
  .command('sources', 'list sources')
  .command('metrics [filter]', 'list metrics')
  .command('spaces', 'list spaces')
  .command('charts [space]', 'list charts on a space')
  .parse(process.argv);
