#!/usr/bin/env node
'use strict';

var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (!args.length) {
  flow.error('You must specify a space id');
  return;
}

var deleteSpace = function(spaceId) {
  var endPoint = config.baseUrl + 'spaces/' + spaceId;
  client.delete(endPoint, function printResponse(data, response) {
                        console.log(JSON.stringify(data, null, 2));
                      });
};

deleteSpace(args[0]);
