#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program
  .usage('<search_name>')
  .parse(process.argv);
var args = program.args;

if (!args.length) {
  program.outputHelp();
  flow.error('You must specify a search string to match the names of spaces against');
  return;
}

var endPoint = config.baseUrl + 'v1/spaces';
client.get(endPoint, function printResponse(data, response) {
                       for (s in data.spaces) {
                         if (data.spaces[s].name == args[0]) {
                           console.log(JSON.stringify(data.spaces[s], null, 2));
                         }
                       }
                     });
