#!/usr/bin/env node
'use strict';

var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

var listMetrics = function(filter) {
  var endPoint = config.baseUrl + 'metrics?name=' + filter;
  client.get(endPoint, function (data, response) {
                         console.log(JSON.stringify(data, null, 2));
                       });
};

if (args.length) {
  listMetrics(args[0]);
} else {
  listMetrics('');
}
