#!/usr/bin/env node
var filesystem = require('fs');
var config = JSON.parse(filesystem.readFileSync('config.json'));

var program = require('commander');
program.parse(process.argv);

var filters = program.args;
var filter = '';

if (filters.length) {
  filter = filters[0];
}

var Client = require('node-rest-client').Client;
var options_auth = { user: config.librato_token, password: config.librato_apikey };

var client = new Client(options_auth);

client.get(config.base_url + "metrics?name=" + filter,
           function (data, response) {
              console.log(JSON.stringify(data, null, 2));
           });
