#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 2) {
  console.error('You must specify a space id to import to chart in to');
  process.exit(1);
}

var importSpace = function(spaceId, chartDefinition) {
  var payload = {
    data: JSON.parse(chartDefinition),
    headers: { "Content-Type": "application/json" }
  };

  var endPoint = config.baseUrl + "spaces/" + spaceId + "/charts";
  client.post(endPoint, payload, function (data, response) {
                                   console.log(response.statusCode + ': ' + response.statusMessage);
                                   console.log(JSON.stringify(data, null, 2));
                                 });
}

importSpace(args[0], args[1]);
