#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 1) {
  flow.error('You must specify a space definition to migrate a space');
  return;
}

var migrateSpace = function(spaceDefinition) {
  spaceDefinition.tags = true;

  spaceDefinition.charts.forEach(function(chart) {
    chart.streams.forEach(function(stream){
      if (stream.type && stream.type === 'composite') {
        stream.composite = stream.composite.replace('\"*\"','{ }');
        stream.composite = stream.composite.replace('\"%\"','{ }');
      }
    });
  });

  console.log(JSON.stringify(spaceDefinition, null, 2));
};

migrateSpace(JSON.parse(args[0]));
