#!/usr/bin/env node
var program = require('commander');
program
  .version('0.3.0')
  .command('list [space id]', 'list all charts that are contained in the specified space')
  .command('export [space id] [chart id]', 'export the specified chart\'s definition in JSON')
  .command('import [space id] [chart definition]', 'imports a JSON chart definition into the specified space')
  .parse(process.argv);
