#!/usr/bin/env node
var program = require('commander');
program
  .version('0.2.0')
  .command('annotate', 'manage librato annotations/events')
  .command('chart', 'manage librato charts')
  .command('metric', 'manage librato metrics')
  .command('source', 'manage librato sources')
  .command('space', 'manage librato spaces')
  .command('config', 'configure librato-cli')
  .parse(process.argv);
