#!/usr/bin/env node
var program = require('commander');
program
  .version('0.2.0')
  .command('list', 'list all librato spaces')
  .command('get [space id]', 'get definition for a librato space')
  .command('byname [terms]', 'get definition for a librato space by its name')
  .command('delete [space id]', 'remove a librato space')
  .command('export [space id]', 'export the definition for a space, including the definitions for its charts, as a JSON file')
  .command('import [space definition]', 'import the definition for a space, as a newly created space')
  .parse(process.argv);
