#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 2) {
  console.error('You must specify a space id and a chart id to export');
  process.exit(1);
}

var removeIdsFromChart = function(chartDefinition) {
  delete chartDefinition.id;

  for(var i = 0; i < chartDefinition.streams.length; i++) {
    delete chartDefinition.streams[i].id;
  }

  return chartDefinition;
};

var exportSpace = function(spaceId, chart) {
  var endPoint = config.baseUrl + "spaces/" + spaceId + "/charts/" + chart;
  client.get(endPoint, function(data, response) {
                         console.log(JSON.stringify(removeIdsFromChart(data), null, 2));
                       });
};

exportSpace(args[0], args[1]);
