#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 1) {
  flow.error('You must specify a space definition to import a space');
  return;
}

var printResponse = function (data, response) {
   console.log(response.statusCode + ': ' + response.statusMessage);
   console.log(JSON.stringify(data, null, 2));
};

var importCharts = function(spaceId, charts) {
  for(var i = 0; i < charts.length; i++) {
    var newChartPayload = {
        data: charts[i],
        headers: { 'Content-Type': 'application/json' }
    };

    var endPoint = config.baseUrl + 'spaces/' + spaceId + '/charts';

    client.post(endPoint, newChartPayload, printResponse);
  }
};

var importSpace = function(spaceDefinition) {
  var spaceConfig = { name: spaceDefinition.name };

  if (spaceDefinition.hasOwnProperty('tags')) {
    spaceConfig['tags'] = spaceDefinition.tags;
  }

  var newSpacePayload = {
    data: JSON.stringify(spaceConfig),
    headers: { 'Content-Type': 'application/json' }
  };

  var endPoint = config.baseUrl + 'spaces';
  client.post(endPoint, newSpacePayload,
             function (data, response) {
                printResponse(data, response);

                var newSpaceId = data.id;
                importCharts(newSpaceId, spaceDefinition.charts);
             });
};

importSpace(JSON.parse(args[0]));
