#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var moment = require('moment');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (!args.length) {
  flow.error('You must specify a metric name');
  return;
}

if (args.length < 2) {
  flow.error('You should supply the number of seconds in the past to query for');
  return;
}

var getMetricOverSpan = function(metricName, startTime, endTime) {
  var endPoint = config.baseUrl + "metrics/" + metricName +
    "?start_time=" + startTime +
    "&end_time=" + endTime + "&resolution=60";
  client.get(endPoint, function (data, response) {
                         console.log(JSON.stringify(data, null, 2));
                         if (data.query && data.query.next_time) {
                           getMetricOverSpan(metricName, data.query.next_time, endTime);
                         }
                       });
};

var getMetric = function(metricName, numberOfSeconds) {
  var startTime = moment().subtract(numberOfSeconds, 'seconds').unix();
  var endTime = moment().unix();

  getMetricOverSpan(metricName, startTime, endTime);
};

getMetric(args[0], args[1]);
