#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (!args.length) {
  flow.error('You must specify the space id to list its charts');
  return;
}

var listCharts = function(spaceId) {
  var endPoint = config.baseUrl + 'spaces/' + spaceId + '/charts';
  client.get(endPoint, function (data, response) {
                         console.log(JSON.stringify(data, null, 2));
                       });
};

listCharts(args[0]);
