#!/usr/bin/env node
var filesystem = require('fs');
var config = JSON.parse(filesystem.readFileSync('config.json'));

var program = require('commander');
program.parse(process.argv);

var spaces = program.args;

if (!spaces.length) {
  console.error('space is required');
  process.exit(1);
}

var space = spaces[0];

var Client = require('node-rest-client').Client;
var options_auth = { user: config.librato_token, password: config.librato_apikey };

var client = new Client(options_auth);

client.get(config.base_url + "spaces/" + space + "/charts",
           function (data, response) {
              console.log(JSON.stringify(data, null, 2));
           });
