#!/usr/bin/env node
var config = require('./modules/librato-cli-config');
var client = require('./modules/librato-cli-client');
var flow = require('./modules/librato-cli-flow');
var program = require('commander');

program.parse(process.argv);
var args = program.args;

if (args.length < 1) {
  flow.error('You must specify the space id of the space you wish to export');
  return;
}

var removeIds = function(data) {
  for(var i = 0; i < data.length; i++) {
    delete data[i].id;

    if (data[i].streams) {
      for(var j = 0; j < data[i].streams.length; j++) {
        delete data[i].streams[j].id;
      }
    }
  }

  return data;
};

var exportCharts = function(spaceId, callback) {
  var endPoint = config.baseUrl + 'spaces/' + spaceId + '/charts';
  client.get(endPoint, function (data, response) {
                         callback(data);
                       });
};

var exportSpace = function(spaceId) {
  var spaceDefinition = { };
  var endPoint = config.baseUrl + 'spaces/' + spaceId;

  client.get(endPoint, function (data, response) {
                         spaceDefinition = removeIds([ data ])[0];
                         exportCharts(spaceId, function(data) {
                           spaceDefinition.charts = removeIds(data);
                           console.log(JSON.stringify(spaceDefinition, null, 2));
                         });
                       });
};

exportSpace(args[0]);
